steps:
  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']  # Deploy to App Engine without asking for confirmation

timeout: '600s'  # Optional: Timeout for the build process (e.g., 10 minutes)
